const ADIL = {
        docteur : {directoryTable:'01_docteur', RequestTable:'01_docteur_setting', FavoriteGenre:'Sante'},
        pharmacie : {directoryTable:'01_pharmacie', RequestTable:'01_docteur_setting', FavoriteGenre:'PTVente'},
        clinique : {directoryTable:'01_clinique', RequestTable:'01_docteur_setting', FavoriteGenre:'Sante'},
        labo : {directoryTable:'01_laboratoire', RequestTable:'01_docteur_setting', FavoriteGenre:'Sante'},
        centreMD : {directoryTable:'01_centre', RequestTable:'01_docteur_setting', FavoriteGenre:'Sante'},
        admin_s_hospital : {directoryTable:'01a_hopitale', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_s_csb : {directoryTable:'01a_centre_sb', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},

        garderie : {directoryTable:'02_garderie', RequestTable:'01_docteur_setting', FavoriteGenre:'Education'},
        ecole : {directoryTable:'02_ecole', RequestTable:'01_docteur_setting', FavoriteGenre:'Education'},
        lycee : {directoryTable:'02_college_lycee', RequestTable:'01_docteur_setting', FavoriteGenre:'Education'},
        universite : {directoryTable:'02_universite', RequestTable:'01_docteur_setting', FavoriteGenre:'Education'},
        impremerie : {directoryTable:'02_impremante', RequestTable:'01_docteur_setting', FavoriteGenre:'Education'},
        librairie : {directoryTable:'02_librairie', RequestTable:'01_docteur_setting', FavoriteGenre:'Education'},
        admin_e_centre : {directoryTable:'02a_centref', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_e_biblio : {directoryTable:'02a_bibliotheque', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_e_ecole : {directoryTable:'02a_ecole', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_e_lycee : {directoryTable:'02a_lycee', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_e_universite : {directoryTable:'02a_universite', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_e_ss : {directoryTable:'02_garderie', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},

        transporteur : {directoryTable:'03_transporteur', RequestTable:'01_docteur_setting', FavoriteGenre:'Transpo'},
        autoecole : {directoryTable:'02_autoecole', RequestTable:'01_docteur_setting', FavoriteGenre:'Transpo'},

        cafe : {directoryTable:' 05_cafe', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        restaurant : {directoryTable:'05_restaurant', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        ptvente_shop : {directoryTable:'05_pv_alimentaire', RequestTable:'01_docteur_setting', FavoriteGenre:'PTVente'},
        ptvente_boulengerie : {directoryTable:'05_pv_boulangerie', RequestTable:'01_docteur_setting', FavoriteGenre:'PTVente'},
        ptvente_viande : {directoryTable:'05_pv_boucheries', RequestTable:'01_docteur_setting', FavoriteGenre:'PTVente'},
        ptvente_fruit : {directoryTable:'05_pv_fruiterie', RequestTable:'01_docteur_setting', FavoriteGenre:'PTVente'},
        ptvente_patesserie : {directoryTable:'05_pv_patisserie', RequestTable:'01_docteur_setting', FavoriteGenre:'PTVente'},

        house_electro : {directoryTable:'04_h_electromenager', RequestTable:'01_docteur_setting', FavoriteGenre:'PTVente'},
        house_meuble : {directoryTable:'04_h_meubles', RequestTable:'01_docteur_setting', FavoriteGenre:'PTVente'},
        car_location : {directoryTable:'04_v_location', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        car_parking : {directoryTable:'04_v_parking', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        car_qiosque : {directoryTable:'04_v_qiosque', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        car_mecanicien : {directoryTable:'04_v_lavage', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},

        samsar : {directoryTable:'09_immobilier_samsar  ', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},
        chantier_contrateur : {directoryTable:'09_c_contracteur', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},
        chantier_architecture : {directoryTable:'09_c_architecture', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},
        chantier_quincaillerie : {directoryTable:'09_c_quincaillerie', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},
        handmade_forgeron : {directoryTable:'09_handmade', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},
        handmade_menuisier : {directoryTable:'09_handmade', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},
        handmade_peinture : {directoryTable:'09_handmade', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},
        handmade_electricien : {directoryTable:'09_handmade', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},
        handmade_plombier : {directoryTable:'09_handmade', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},
        handmade_cristal : {directoryTable:'09_handmade', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},
        handmade_marbre : {directoryTable:'09_handmade', RequestTable:'01_docteur_setting', FavoriteGenre:'Construct'},

        coiffure : {directoryTable:'04_coiffure', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        boutique : {directoryTable:'04_boutique', RequestTable:'01_docteur_setting', FavoriteGenre:'PTVente'},
        wedding_salon_marriage : {directoryTable:'04_m_salon_marriage', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        wedding_orchestre : {directoryTable:'04_m_orchestre', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        wedding_chef : {directoryTable:'04_m_chef', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        wedding_photographe : {directoryTable:'04_m_photographe', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        wedding_fourniture_marriage : {directoryTable:'04_m_fourniture_marriage', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        wedding_bijoux : {directoryTable:'04_m_bijoux', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},

        gym : {directoryTable:'06_sport_salle', RequestTable:'01_docteur_setting', FavoriteGenre:'Sport'},
        pyscine : {directoryTable:'06_pycine', RequestTable:'01_docteur_setting', FavoriteGenre:'Sport'},
        stade : {directoryTable:'06_stade', RequestTable:'01_docteur_setting', FavoriteGenre:'Sport'},
        art_cinema : {directoryTable:'06_cinema', RequestTable:'01_docteur_setting', FavoriteGenre:'Sport'},
        art_theatre : {directoryTable:'06_theatre', RequestTable:'01_docteur_setting', FavoriteGenre:'Sport'},
        art_musee : {directoryTable:'06_musee', RequestTable:'01_docteur_setting', FavoriteGenre:'Sport'},
        admin_c_mj : {directoryTable:'06a_jeune_ma', RequestTable:'01_docteur_setting', FavoriteGenre:'Sport'},
        admin_c_mc : {directoryTable:'06a_culture_ma', RequestTable:'01_docteur_setting', FavoriteGenre:'Sport'},
        admin_c_me : {directoryTable:'06a_enfant_ma', RequestTable:'01_docteur_setting', FavoriteGenre:'Sport'},

        avocat : {directoryTable:'10_avocat', RequestTable:'01_docteur_setting', FavoriteGenre:'Other'},

        storage : {directoryTable:'08_vente_en_gros ', RequestTable:'01_docteur_setting', FavoriteGenre:'PTVente'},
        comptable : {directoryTable:'08_socite', RequestTable:'01_docteur_setting', FavoriteGenre:'Other'},
        socite : {directoryTable:'08_socite', RequestTable:'01_docteur_setting', FavoriteGenre:'Other'},
        admin_f_poste : {directoryTable:'08a_poste', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_f_rf : {directoryTable:'08a_recipe', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},

        hotels : {directoryTable:'07_hotels', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},
        vg_agence : {directoryTable:'07_agence', RequestTable:'01_docteur_setting', FavoriteGenre:'Life'},

        admin_a_mu : {directoryTable:'00_municipalite', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_a_police : {directoryTable:'00_police', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_a_ar : {directoryTable:'00_admin_regionale', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_a_court : {directoryTable:'00_cour', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        admin_a_mosq : {directoryTable:'00_mosquee', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
        ambassade : {directoryTable:'00_ambassade', RequestTable:'01_docteur_setting', FavoriteGenre:'Admin'},
}

module.exports = ADIL